export interface RsvpItem {
  createdAt: number; 
  eventId: string;
  userId: string;
}

export interface RsvpProfile {
  gradYear: number;
  gradMonth: string;
  expectedDegree: string;
  intendedMajor: string;
  interests: string[];
  dietaryRestrictions: string[];
  updatedAt: number;
}

export interface MyProfileViewProps {
  getProfile: () => Promise<RsvpProfile | null>;
  updateProfile: (profile: Omit<RsvpProfile, 'updatedAt'>, turnstileToken: string) => Promise<void>;
  isFirstTime: boolean;
}

export const SCHOOL_YEARS = ["Freshman", "Sophomore", "Junior", "Senior", "Graduate"];

export const MAJORS = [
  "ACES Undeclared",
  "Accountancy",
  "Accountancy + Data Science",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural & Biological Engineering",
  "Agricultural & Consumer Economics",
  "Agricultural Leadership, Education, & Communications",
  "Agronomy",
  "Animal Sciences",
  "Anthropology",
  "Architectural Studies",
  "Art & Art History",
  "Art Education",
  "Art History",
  "Art Undeclared",
  "Asian American Studies",
  "Astronomy",
  "Astronomy + Data Science",
  "Astrophysics",
  "Atmospheric Sciences",
  "Biochemistry",
  "Bioengineering",
  "Brain & Cognitive Science",
  "Business + Data Science",
  "Business Undeclared",
  "Chemical Engineering",
  "Chemical Engineering + Data Science",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Communication",
  "Community Health",
  "Comparative & World Literature",
  "Computer Engineering",
  "Computer Science",
  "Computer Science + Advertising",
  "Computer Science + Animal Sciences",
  "Computer Science + Anthropology",
  "Computer Science + Astronomy",
  "Computer Science + Bioengineering",
  "Computer Science + Chemistry",
  "Computer Science + Crop Sciences",
  "Computer Science + Economics",
  "Computer Science + Education",
  "Computer Science + Geography & Geographic Information Science",
  "Computer Science + Linguistics",
  "Computer Science + Music",
  "Computer Science + Philosophy",
  "Computer Science + Physics",
  "Creative Writing",
  "Crop Sciences",
  "Dance",
  "Dietetics and Nutrition",
  "Early Childhood Education",
  "Earth, Society, & Environmental Sustainability",
  "East Asian Languages & Cultures",
  "Econometrics & Quantitative Economics",
  "Economics",
  "Electrical Engineering",
  "Elementary Education",
  "Engineering Mechanics",
  "Engineering Technology & Management for Agricultural Systems",
  "Engineering Undeclared",
  "English",
  "Environmental Engineering",
  "Finance",
  "Finance + Data Science",
  "Food Science",
  "French",
  "French (Teaching)",
  "Gender & Women's Studies",
  "Geography & Geographic Information Science",
  "Geology",
  "German (Teaching)",
  "Germanic Studies",
  "Global Studies",
  "Graphic Design",
  "History",
  "History of Art",
  "Hospitality Management",
  "Human Development & Family Studies",
  "Individual Plans of Study",
  "Industrial Design",
  "Industrial Engineering",
  "Information Sciences",
  "Information Sciences + Data Science",
  "Information Systems",
  "Innovation, Leadership & Engineering Entrepreneurship",
  "Instrumental Music",
  "Integrative Biology",
  "Interdisciplinary Health Sciences",
  "Interdisciplinary Studies",
  "Italian",
  "Jazz Performance",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Latin American Studies",
  "Latina/Latino Studies",
  "Learning & Education Studies",
  "Liberal Studies",
  "Linguistics",
  "Linguistics and TESL",
  "Lyric Theatre",
  "Management",
  "Marketing",
  "Materials Science & Engineering",
  "Materials Science & Engineering + Data Science",
  "Mathematics",
  "Mathematics & Computer Science",
  "Mechanical Engineering",
  "Media",
  "Media & Cinema Studies",
  "Middle Grades Education",
  "Molecular & Cellular Biology",
  "Molecular and Cellular Biology + Data Science",
  "Music",
  "Music Composition",
  "Music Education",
  "Music Technology",
  "Musicology",
  "Natural Resources & Environmental Sciences",
  "Neural Engineering",
  "Neuroscience",
  "Nuclear, Plasma, & Radiological Engineering",
  "Nuclear, Plasma, and Radiological Engineering + Data Science",
  "Nutrition and Health",
  "Operations Management",
  "Philosophy",
  "Physics",
  "Plant Biotechnology",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Recreation, Sport & Tourism",
  "Religion",
  "Russian, East European, & Eurasian Studies",
  "Secondary Education",
  "Slavic Studies",
  "Social Work",
  "Sociology",
  "Spanish",
  "Spanish (Teaching)",
  "Special Education",
  "Speech & Hearing Science",
  "Statistics",
  "Statistics & Computer Science",
  "Strategy, Innovation and Entrepreneurship",
  "Studio Art",
  "Supply Chain Management",
  "Sustainability in Food & Environmental Systems",
  "Sustainable Design",
  "Systems Engineering and Design",
  "Teaching - Middle Grades Education",
  "Theatre",
  "Urban Studies & Planning",
  "Voice"
];

export const COMMON_INTERESTS = [
  "AI/Machine Learning",
  "Web Development",
  "Mobile Development",
  "Cybersecurity",
  "Game Development",
  "Data Science",
  "Cloud Computing",
  "Robotics",
  "Blockchain",
  "UI/UX Design"
];